services:
  - type: web
    name: wompi-api
    env: node
    buildCommand: bun install && bun run build
    startCommand: bun run start:prod
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: wompi-api
          property: port