services:
  - type: web
    name: wompi-api
    env: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true